[package]
name = "webrtc-example-rustside"
version = "0.1.0"
edition = "2024"

[dependencies]
webrtc = "0.9"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22.1"
